repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=pandoc]
    -   id: check-added-large-files
        args: [--maxkb 1024]
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
-   repo: local
    hooks:
    -   id: file-names
        name: Check file names
        entry: scripts/hooks/pre-commit-file-names.sh
        language: system
        stages: [commit, manual]
        verbose: true

exclude: 'ThirdParty/*|Tests/Data/*|web/static/images/xsd'
